version: '3.3'
services:
  db:
    container_name: database
    image: postgres
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
          POSTGRES_PASSWORD: password
volumes:
  db_data: {}
