name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x Movie/gradlew 

      - name: Install dependencies
        run: ./gradlew build
        working-directory: Movie

      - name: Run tests
        run: ./gradlew test
        working-directory: Movie
