name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x Movie/gradlew 
      - name: Run PostgreSQL container
        run: |
          docker run --name postgresdss -d -e POSTGRES_PASSWORD=passddword -e POSTGRES_DB=postgres -p 5439:5432 postgres
     
      - name: Run tests
        run: ./gradlew test
        working-directory: Movie
